In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import seaborn as sns

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error
from sklearn.tree import DecisionTreeRegressor

In [13]:
df = pd.read_csv('AQ_data.csv',low_memory=False )
df

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
0,150,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",4.8,17.4,NaN,NaN,NaN,NaN,1990-02-01
1,151,February - M021990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,3.1,7.0,NaN,NaN,NaN,NaN,1990-02-01
2,152,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.2,28.5,NaN,NaN,NaN,NaN,1990-02-01
3,150,March - M031990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.3,14.7,NaN,NaN,NaN,NaN,1990-03-01
4,151,March - M031990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,4.7,7.5,NaN,NaN,NaN,NaN,1990-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
435737,SAMP,24-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,22.0,50.0,143.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,2015-12-24
435738,SAMP,29-12-15,West Bengal,ULUBERIA,West Bengal State Pollution Control Board,RIRUO,20.0,46.0,171.0,NaN,"Inside Rampal Industries,ULUBERIA",NaN,2015-12-29
435739,NaN,NaN,andaman-and-nicobar-islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435740,NaN,NaN,Lakshadweep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435741,NaN,NaN,Tripura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Data cleaning 



# 1 remove nulls 

df.isnull().sum()

stn_code                       144077
sampling_date                       3
state                               0
location                            3
agency                         149481
type                             5393
so2                             34646
no2                             16233
rspm                            40222
spm                            237387
location_monitoring_station     27491
pm2_5                          426428
date                                7
dtype: int64

In [22]:
#remove columns with too many nulls 
# first lets see column names and clean extra spaces 

df.columns = df.columns.str.strip()
# Drop columns with too many nulls (optional)
df.drop(['agency', 'location_monitoring_station'], axis=1, inplace=True)

In [24]:
#fill missing values with mean

df.fillna(df.mean(numeric_only=True), inplace =True)
df

,stn_code,sampling_date,state,location,type,so2,no2,rspm,spm,pm2_5,date
0,150,February - M021990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",4.800000,17.400000,108.832784,220.78348,40.791467,1990-02-01
1,151,February - M021990,Andhra Pradesh,Hyderabad,Industrial Area,3.100000,7.000000,108.832784,220.78348,40.791467,1990-02-01
2,152,February - M021990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.200000,28.500000,108.832784,220.78348,40.791467,1990-02-01
3,150,March - M031990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.300000,14.700000,108.832784,220.78348,40.791467,1990-03-01
4,151,March - M031990,Andhra Pradesh,Hyderabad,Industrial Area,4.700000,7.500000,108.832784,220.78348,40.791467,1990-03-01
...,...,...,...,...,...,...,...,...,...,...,...
435737,SAMP,24-12-15,West Bengal,ULUBERIA,RIRUO,22.000000,50.000000,143.000000,220.78348,40.791467,2015-12-24
435738,SAMP,29-12-15,West Bengal,ULUBERIA,RIRUO,20.000000,46.000000,171.000000,220.78348,40.791467,2015-12-29
435739,NaN,NaN,andaman-and-nicobar-islands,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaN
435740,NaN,NaN,Lakshadweep,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaN
435741,NaN,NaN,Tripura,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaN

In [26]:
#remove duplicate rows if any

df.drop_duplicates(inplace=True)

In [27]:
df.dtypes

stn_code          object
sampling_date     object
state             object
location          object
type              object
so2              float64
no2              float64
rspm             float64
spm              float64
pm2_5            float64
date              object
dtype: object

In [29]:
df['stn_code'] = pd.to_numeric(df['stn_code'], errors='coerce')

df.dtypes

stn_code         float64
sampling_date     object
state             object
location          object
type              object
so2              float64
no2              float64
rspm             float64
spm              float64
pm2_5            float64
date              object
dtype: object

In [30]:
df['stn_code'] = pd.to_numeric(df['stn_code'] , errors='coerce')

In [34]:
#drop useless samppling column

df.drop(['sampling_date'] , inplace=True , errors='ignore' , axis=1)
df

,stn_code,state,location,type,so2,no2,rspm,spm,pm2_5,date
0,150.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",4.800000,17.400000,108.832784,220.78348,40.791467,1990-02-01
1,151.0,Andhra Pradesh,Hyderabad,Industrial Area,3.100000,7.000000,108.832784,220.78348,40.791467,1990-02-01
2,152.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.200000,28.500000,108.832784,220.78348,40.791467,1990-02-01
3,150.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.300000,14.700000,108.832784,220.78348,40.791467,1990-03-01
4,151.0,Andhra Pradesh,Hyderabad,Industrial Area,4.700000,7.500000,108.832784,220.78348,40.791467,1990-03-01
...,...,...,...,...,...,...,...,...,...,...
435737,NaN,West Bengal,ULUBERIA,RIRUO,22.000000,50.000000,143.000000,220.78348,40.791467,2015-12-24
435738,NaN,West Bengal,ULUBERIA,RIRUO,20.000000,46.000000,171.000000,220.78348,40.791467,2015-12-29
435739,NaN,andaman-and-nicobar-islands,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaN
435740,NaN,Lakshadweep,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaN
435741,NaN,Tripura,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaN

In [36]:
#data integration 


df['date'] = pd.to_datetime(df['date'] )
df.dtypes

stn_code           float64
state               object
location            object
type                object
so2                float64
no2                float64
rspm               float64
spm                float64
pm2_5              float64
date        datetime64[ns]
dtype: object

In [39]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df

,stn_code,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,month
0,150.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",4.800000,17.400000,108.832784,220.78348,40.791467,1990-02-01,1990.0,2.0
1,151.0,Andhra Pradesh,Hyderabad,Industrial Area,3.100000,7.000000,108.832784,220.78348,40.791467,1990-02-01,1990.0,2.0
2,152.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.200000,28.500000,108.832784,220.78348,40.791467,1990-02-01,1990.0,2.0
3,150.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.300000,14.700000,108.832784,220.78348,40.791467,1990-03-01,1990.0,3.0
4,151.0,Andhra Pradesh,Hyderabad,Industrial Area,4.700000,7.500000,108.832784,220.78348,40.791467,1990-03-01,1990.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
435737,NaN,West Bengal,ULUBERIA,RIRUO,22.000000,50.000000,143.000000,220.78348,40.791467,2015-12-24,2015.0,12.0
435738,NaN,West Bengal,ULUBERIA,RIRUO,20.000000,46.000000,171.000000,220.78348,40.791467,2015-12-29,2015.0,12.0
435739,NaN,andaman-and-nicobar-islands,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaT,NaN,NaN
435740,NaN,Lakshadweep,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaT,NaN,NaN
435741,NaN,Tripura,NaN,NaN,10.829414,25.809623,108.832784,220.78348,40.791467,NaT,NaN,NaN

In [41]:
from sklearn.preprocessing import StandardScaler

In [44]:
#object bana liya 
scaler = StandardScaler()

#select numeriic columns

num_cols = ['so2','no2','rspm','spm','pm2_5']

In [46]:
#apply normalization

df[num_cols] = scaler.fit_transform(df[num_cols])

In [47]:
df

,stn_code,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,month
0,150.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",-0.562712,-0.464028,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0
1,151.0,Andhra Pradesh,Hyderabad,Industrial Area,-0.721367,-1.037019,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0
2,152.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",-0.432055,0.147528,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0
3,150.0,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",-0.422723,-0.612786,-0.000513,0.000013,0.0,1990-03-01,1990.0,3.0
4,151.0,Andhra Pradesh,Hyderabad,Industrial Area,-0.572045,-1.009471,-0.000513,0.000013,0.0,1990-03-01,1990.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
435737,NaN,West Bengal,ULUBERIA,RIRUO,1.042501,1.332075,0.478222,0.000013,0.0,2015-12-24,2015.0,12.0
435738,NaN,West Bengal,ULUBERIA,RIRUO,0.855848,1.111694,0.870544,0.000013,0.0,2015-12-29,2015.0,12.0
435739,NaN,andaman-and-nicobar-islands,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN
435740,NaN,Lakshadweep,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN
435741,NaN,Tripura,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN

In [52]:
# Convert categorical to numeric
df

,stn_code,location,so2,no2,rspm,spm,pm2_5,date,year,month,...,state_andaman-and-nicobar-islands,type_Industrial Area,type_Industrial Areas,type_RIRUO,type_Residential,type_Residential and others,"type_Residential, Rural and other Areas",type_Sensitive,type_Sensitive Area,type_Sensitive Areas
0,150.0,Hyderabad,-0.562712,-0.464028,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0,...,False,False,False,False,False,False,True,False,False,False
1,151.0,Hyderabad,-0.721367,-1.037019,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0,...,False,True,False,False,False,False,False,False,False,False
2,152.0,Hyderabad,-0.432055,0.147528,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0,...,False,False,False,False,False,False,True,False,False,False
3,150.0,Hyderabad,-0.422723,-0.612786,-0.000513,0.000013,0.0,1990-03-01,1990.0,3.0,...,False,False,False,False,False,False,True,False,False,False
4,151.0,Hyderabad,-0.572045,-1.009471,-0.000513,0.000013,0.0,1990-03-01,1990.0,3.0,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435737,NaN,ULUBERIA,1.042501,1.332075,0.478222,0.000013,0.0,2015-12-24,2015.0,12.0,...,False,False,False,True,False,False,False,False,False,False
435738,NaN,ULUBERIA,0.855848,1.111694,0.870544,0.000013,0.0,2015-12-29,2015.0,12.0,...,False,False,False,True,False,False,False,False,False,False
435739,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
435740,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
435741,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False

In [54]:
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].astype(int)

In [55]:
df

,stn_code,location,so2,no2,rspm,spm,pm2_5,date,year,month,...,state_andaman-and-nicobar-islands,type_Industrial Area,type_Industrial Areas,type_RIRUO,type_Residential,type_Residential and others,"type_Residential, Rural and other Areas",type_Sensitive,type_Sensitive Area,type_Sensitive Areas
0,150.0,Hyderabad,-0.562712,-0.464028,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0,...,0,0,0,0,0,0,1,0,0,0
1,151.0,Hyderabad,-0.721367,-1.037019,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0,...,0,1,0,0,0,0,0,0,0,0
2,152.0,Hyderabad,-0.432055,0.147528,-0.000513,0.000013,0.0,1990-02-01,1990.0,2.0,...,0,0,0,0,0,0,1,0,0,0
3,150.0,Hyderabad,-0.422723,-0.612786,-0.000513,0.000013,0.0,1990-03-01,1990.0,3.0,...,0,0,0,0,0,0,1,0,0,0
4,151.0,Hyderabad,-0.572045,-1.009471,-0.000513,0.000013,0.0,1990-03-01,1990.0,3.0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435737,NaN,ULUBERIA,1.042501,1.332075,0.478222,0.000013,0.0,2015-12-24,2015.0,12.0,...,0,0,0,1,0,0,0,0,0,0
435738,NaN,ULUBERIA,0.855848,1.111694,0.870544,0.000013,0.0,2015-12-29,2015.0,12.0,...,0,0,0,1,0,0,0,0,0,0
435739,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN,...,1,0,0,0,0,0,0,0,0,0
435740,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
435741,NaN,NaN,-0.000009,-0.000699,-0.000513,0.000013,0.0,NaT,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [57]:
# model building 

#define x and y 

x = df[['so2','no2','rspm','spm']]
y = df['pm2_5']

In [58]:
x

             so2       no2      rspm       spm
0      -0.562712 -0.464028 -0.000513  0.000013
1      -0.721367 -1.037019 -0.000513  0.000013
2      -0.432055  0.147528 -0.000513  0.000013
3      -0.422723 -0.612786 -0.000513  0.000013
4      -0.572045 -1.009471 -0.000513  0.000013
...          ...       ...       ...       ...
435737  1.042501  1.332075  0.478222  0.000013
435738  0.855848  1.111694  0.870544  0.000013
435739 -0.000009 -0.000699 -0.000513  0.000013
435740 -0.000009 -0.000699 -0.000513  0.000013
435741 -0.000009 -0.000699 -0.000513  0.000013

[434944 rows x 4 columns]

In [59]:
y

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
435737    0.0
435738    0.0
435739    0.0
435740    0.0
435741    0.0
Name: pm2_5, Length: 434944, dtype: float64

In [60]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size =0.2)

In [61]:
model = LinearRegression()

In [62]:
model.fit(x_train,y_train)

LinearRegression()

In [64]:
y_pred = model.predict(x_test)

In [65]:
print("R2 Score:", r2_score(y_test , y_pred))

R2 Score: 0.010441200828130937

In [66]:
print ("MAE:" , mean_absolute_error(y_test,y_pred))

MAE: 0.15899142641396394

In [69]:
model_1 = DecisionTreeRegressor()
model_1.fit(x_train, y_train)

y_pred = model_1.predict(x_test)

print("R2:", r2_score(y_test, y_pred))

R2: -0.7025139851430482