In [6]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('dataset_Facebook.csv',sep=";")

In [5]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [16]:
#data subset

subset_1 = df[['Type','Lifetime Post reach by people who like your Page']]

In [17]:
subset_1

       Type  Lifetime Post reach by people who like your Page
0     Photo                                              1640
1    Status                                              6112
2     Photo                                              1503
3     Photo                                             32048
4     Photo                                              3200
..      ...                                               ...
495   Photo                                              2876
496   Photo                                              2104
497   Photo                                              2388
498   Photo                                              2452
499   Photo                                              2200

[500 rows x 2 columns]

In [19]:
subset_2  = df[['Type','Post Month', 'comment']]
subset_2

       Type  Post Month  comment
0     Photo          12        4
1    Status          12        5
2     Photo          12        0
3     Photo          12       58
4     Photo          12       19
..      ...         ...      ...
495   Photo           1        5
496   Photo           1        0
497   Photo           1        4
498   Photo           1        7
499   Photo           1        0

[500 rows x 3 columns]

In [22]:
merged_subset = pd.concat([subset_1,subset_2] , axis =1)
merged_subset

,Type,Lifetime Post reach by people who like your Page,Type,Post Month,comment
0,Photo,1640,Photo,12,4
1,Status,6112,Status,12,5
2,Photo,1503,Photo,12,0
3,Photo,32048,Photo,12,58
4,Photo,3200,Photo,12,19
...,...,...,...,...,...
495,Photo,2876,Photo,1,5
496,Photo,2104,Photo,1,0
497,Photo,2388,Photo,1,4
498,Photo,2452,Photo,1,7
499,Photo,2200,Photo,1,0

In [28]:
soreted = df.sort_values(by='Lifetime Post Total Reach' , ascending = False)
soreted

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.0,313
463,92186,Photo,3,2,7,2,1.0,153536,497910,1713,1633,2493,8907,5696,593,8,134.0,34.0,176
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
380,111620,Photo,1,4,7,14,0.0,128064,251269,1539,1408,2506,84046,32384,985,8,186.0,18.0,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.0,6
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,NaN,2
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.0,5
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.0,7
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.0,2

In [29]:
transposed_df = merged_subset.transpose()
transposed_df

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0

In [30]:
print(df.shape)

(500, 19)

In [34]:
# reshape 

arr = np.array(df[['Post Month', 'Post Weekday']].head(6))
reshaped = arr.reshape(3,4)
reshaped

array([[12,  4, 12,  3],
       [12,  3, 12,  2],
       [12,  2, 12,  1]])

In [37]:
arrr = np.array(df[['Post Month','Post Weekday']].head(6))

reshaped_daata = arrr.reshape(4,3)
reshaped_daata

array([[12,  4, 12],
       [ 3, 12,  3],
       [12,  2, 12],
       [ 2, 12,  1]])