## Web Scraping Using Python

Website to be scraped - https://books.toscrape.com/catalogue/page-1.html

In [11]:
# Run these instructions in command prompt
# pip install bs4
# pip install requests

**Import necessary libraries**

In [12]:
import requests
import bs4
import pandas as pd

**Send request using URL of the webpage to be scraped**
To establish the connection between python environment that we are using and the webpage to be scraped, we use requests library.

In [14]:
# accessing second page of the website
request1 = requests.get('http://books.toscrape.com/catalogue/page-2.html')

In [15]:
# status 200 means connection successful
print(request1)

<Response [200]>

**Create soup object using BeautifulSoup library used for web scraping which returns HTML code of the webpage**

In [ ]:
soup = bs4.BeautifulSoup(request1.text)
soup

**Go to the webpage and right click, hit 'inspect'. HTML code of that block will appear on right side of the webpage**

**To choose any HTML tag, use `select` method**

Let’s try selecting `article` tag. This tag gives me all the information of about each book.

In [ ]:
soup.select('article')

**To select tags inside tag :**

In [18]:
soup.select('article h3 a')

[<a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a>,
 <a href="how-music-works_979/index.html" title="How Music Works">How Music Works</a>,
 <a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">Foolproof Preserving: A Guide ...</a>,
 <a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a>,
 <a href="black-dust_976/index.html" title="Black Dust">Black Dust</a>,
 <a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">Birdsong: A Story in ...</a>,
 <a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana">America's Cradle of Quarterbacks: ...</a>,
 <a href="aladdin-and-his-wonderful-lamp_973/index.html" title="Aladdin and His Wonderful Lamp">Aladdin and His Wonderful ...</a>,
 <a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html" title="Worlds Elsewhere: Journeys Around Shakespeareâs Globe">Worlds Elsewhere: Journeys Around ...</a>,
 <a href="wall-and-piece_971/index.html" title="Wall and Piece">Wall and Piece</a>,
 <a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html" title="The Four Agreements: A Practical Guide to Personal Freedom">The Four Agreements: A ...</a>,
 <a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html" title="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate">The Five Love Languages: ...</a>,
 <a href="the-elephant-tree_968/index.html" title="The Elephant Tree">The Elephant Tree</a>,
 <a href="the-bear-and-the-piano_967/index.html" title="The Bear and the Piano">The Bear and the ...</a>,
 <a href="sophies-world_966/index.html" title="Sophie's World">Sophie's World</a>,
 <a href="penny-maybe_965/index.html" title="Penny Maybe">Penny Maybe</a>,
 <a href="maude-1883-1993she-grew-up-with-the-country_964/index.html" title="Maude (1883-1993):She Grew Up with the country">Maude (1883-1993):She Grew Up ...</a>,
 <a href="in-a-dark-dark-wood_963/index.html" title="In a Dark, Dark Wood">In a Dark, Dark ...</a>,
 <a href="behind-closed-doors_962/index.html" title="Behind Closed Doors">Behind Closed Doors</a>,
 <a href="you-cant-bury-them-all-poems_961/index.html" title="You can't bury them all: Poems">You can't bury them ...</a>]

**Let's check the lentgh of a list since `select` method returns a list**

In [19]:
len(soup.select('article h3 a'))

20

**So there are 20 books on  a single webpage**

In [22]:
# inspecting any element in the list
soup.select('article h3 a')[0]

In [23]:
# accessing the name of book ( similar to key-value pair in Python dictionary )
soup.select('article h3 a')[0]['title']

'In Her Wake'

In [24]:
# accessing the link of each book ( similar to key-value pair in Python dictionary )
soup.select('article h3 a')[0]['href']

'in-her-wake_980/index.html'

**Let's look for rating of each book in `article` tag**

In [ ]:
soup.select('article p')

In [25]:
# inspecting first element of a list
(soup.select('article p'))[0]

<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>

In [26]:
# accessing the class
(soup.select('article p'))[0]['class']

['star-rating', 'One']

In [27]:
(soup.select('article p'))[0]['class'][1]

'One'

**Using for loop to get the names of all the books and their rating**

In [29]:
title_list = []
rating_list = []

for page_num in range(1,51):  # total pages
    req_page = requests.get(f'http://books.toscrape.com/catalogue/page-{page_num}.html')  # url of each page
    soup_page = bs4.BeautifulSoup(req_page.text)

    for item in soup_page.select('article h3 a'):
        title_list.append(item['title'])

    for n in range(0,60,3):
        rating_list.append(soup_page.select('article p')[n]['class'][1])

In [32]:
   d1 = dict(zip(title_list, rating_list))  # making dictionary with features as titles and ratings
   new = pd.DataFrame.from_dict(d1,orient='index')
   print(new)

                                                        0
A Light in the Attic                                Three
Tipping the Velvet                                    One
Soumission                                            One
Sharp Objects                                        Four
Sapiens: A Brief History of Humankind                Five
...                                                   ...
Alice in Wonderland (Alice's Adventures in Wond...    One
Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)     Four
A Spy's Devotion (The Regency Spies of London #1)    Five
1st to Die (Women's Murder Club #1)                   One
1,000 Places to See Before You Die                   Five

[999 rows x 1 columns]

In [31]:
print(new.shape)

(999, 1)

In [33]:
new.to_csv('scraped_dataset1.csv')

In [34]:
import os
current_directory = os.getcwd()
print(current_directory)

/content

In [35]:
new_books_df=pd.read_csv("scraped_dataset1.csv")
new_books_df.head(5)

                              Unnamed: 0      0
0                   A Light in the Attic  Three
1                     Tipping the Velvet    One
2                             Soumission    One
3                          Sharp Objects   Four
4  Sapiens: A Brief History of Humankind   Five

In [ ]:
print(title_list)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas", 'In Her Wake', 'How Music Works', 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More', 'Chase Me (Paris Nights #2)', 'Black Dust', 'Birdsong: A Story in Pictures', "America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana", 'Aladdin and His Wonderful Lamp', 'Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 'Wall and Piece', 'The Four Agreements: A Practical Guide to Personal Freedom', 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate', 'The Elephant Tree', 'The Bear and the Piano', "Sophie's World", 'Penny Maybe', 'Maude (1883-1993):She Grew Up with the country', 'In a Dark, Dark Wood', 'Behind Closed Doors', "You can't bury them all: Poems", 'Slow States of Collapse: Poems', 'Reasons to Stay Alive', 'Private Paris (Private #10)', '#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 'Without Borders (Wanderlove #1)', 'When We Collided', 'We Love You, Charlie Freeman', 'Untitled Collection: Sabbath Poems 2014', 'Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness', 'Unicorn Tracks', 'Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink', 'Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)', 'Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity', 'This One Summer', 'Thirst', 'The Torch Is Passed: A Harding Family Story', 'The Secret of Dreadwillow Carse', 'The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!', 'The Past Never Ends', 'The Natural History of Us (The Fine Art of Pretending #2)', 'The Nameless City (The Nameless City #1)', 'The Murder That Never Was (Forensic Instincts #5)', "The Most Perfect Thing: Inside (and Outside) a Bird's Egg", 'The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy', 'The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing', 'The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 'The Gutsy Girl: Escapades for Your Life of Epic Adventure', 'The Electric Pencil: Drawings from Inside State Hospital No. 3', 'The Death of Humanity: and the Case for Life', 'The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life', 'The Art Forger', 'The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind', "The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution", 'Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up', 'Soul Reader', 'Security', 'Saga, Volume 6 (Saga (Collected Editions) #6)', 'Saga, Volume 5 (Saga (Collected Editions) #5)', 'Reskilling America: Learning to Labor in the Twenty-First Century', 'Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)', 'Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)', 'Princess Between Worlds (Wide-Awake Princess #5)', 'Pop Gun War, Volume 1: Gift', 'Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics', 'Patience', 'Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)', 'orange: The Complete Collection 1 (orange: The Complete Collection #1)', 'Online Marketing for Busy Authors: A Step-By-Step Guide', 'On a Midnight Clear', 'Obsidian (Lux #1)', 'My Paris Kitchen: Recipes and Stories', 'Masks and Shadows', 'Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed', 'Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)', 'Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)', 'Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)', 'Layered: Baking, Building, and Styling Spectacular Cakes', 'Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)', 'Join', 'In the Country We Love: My Family Divided', 'Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine', 'I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)', 'I am a Hero Omnibus Volume 1', 'How to Be Miserable: 40 Strategies You Already Use', 'Her Backup Boyfriend (The Sorensen Family #1)', 'Giant Days, Vol. 2 (Giant Days #5-8)', 'Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton', 'First and First (Five Boroughs #3)', 'Fifty Shades Darker (Fifty Shades #2)', 'Everydata: The Misinformation Hidden in the Little Data You Consume Every Day', "Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master", 'Danganronpa Volume 1', 'Crown of Midnight (Throne of Glass #2)', 'Codename Baboushka, Volume 1: The Conclave of Death', 'Camp Midnight', 'Call the Nurse: True Stories of a Country Nurse on a Scottish Isle', 'Burning', 'Bossypants', 'Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))', 'Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)', 'Algorithms to Live By: The Computer Science of Human Decisions', 'A World of Flavor: Your Gluten Free Passport', 'A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations', 'A Murder in Time', 'A Flight of Arrows (The Pathfinders #2)', 'A Fierce and Subtle Poison', 'A Court of Thorns and Roses (A Court of Thorns and Roses #1)', '(Un)Qualified: How God Uses Broken People to Do Big Things', 'You Are What You Love: The Spiritual Power of Habit', "William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)", 'Tuesday Nights in 1980', 'Tracing Numbers on a Train', 'Throne of Glass (Throne of Glass #1)', 'Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History', 'Thirteen Reasons Why', 'The White Cat and the Monk: A Retelling of the Poem â\x80\x9cPangur BÃ¡nâ\x80\x9d', 'The Wedding Dress', 'The Vacationers', 'The Third Wave: An Entrepreneurâ\x80\x99s Vision of the Future', 'The Stranger', 'The Shadow Hero (The Shadow Hero)', 'The Secret (The Secret #1)', 'The Regional Office Is Under Attack!', 'The Psychopath Test: A Journey Through the Madness Industry', 'The Project', 'The Power of Now: A Guide to Spiritual Enlightenment', "The Omnivore's Dilemma: A Natural History of Four Meals", 'The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us', 'The Murder of Roger Ackroyd (Hercule Poirot #4)', 'The Mistake (Off-Campus #2)', "The Matchmaker's Playbook (Wingmen Inc. #1)", 'The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking', 'The Long Shadow of Small Ghosts: Murder and Memory in an American City', 'The Kite Runner', 'The House by the Lake', 'The Glittering Court (The Glittering Court #1)', 'The Girl on the Train', 'The Genius of Birds', 'The Emerald Mystery', 'The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First', "The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.", "The Artist's Way: A Spiritual Path to Higher Creativity", 'The Art of War', 'The Argonauts', 'The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job', 'Suddenly in Love (Lake Haven #1)', 'Something More Than This', 'Soft Apocalypse', "So You've Been Publicly Shamed", 'Shoe Dog: A Memoir by the Creator of NIKE', 'Shobu Samurai, Project Aryoku (#3)', 'Secrets and Lace (Fatal Hearts #1)', 'Scarlett Epstein Hates It Here', 'Romero and Juliet: A Tragic Tale of Love and Zombies', 'Redeeming Love', 'Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form', 'Poems That Make Grown Women Cry', 'Nightingale, Sing', 'Night Sky with Exit Wounds', 'Mrs. Houdini', 'Modern Romance', 'Miss Peregrineâ\x80\x99s Home for Peculiar Children (Miss Peregrineâ\x80\x99s Peculiar Children #1)', 'Louisa: The Extraordinary Life of Mrs. Adams', 'Little Red', 'Library of Souls (Miss Peregrineâ\x80\x99s Peculiar Children #3)', 'Large Print Heart of the Pride', 'I Had a Nice Time And Other Lies...: How to find love & sh*t like that', 'Hollow City (Miss Peregrineâ\x80\x99s Peculiar Children #2)', 'Grumbles', 'Full Moon over Noahâ\x80\x99s Ark: An Odyssey to Mount Ararat and Beyond', 'Frostbite (Vampire Academy #2)', 'Follow You Home', 'First Steps for New Christians (Print Edition)', 'Finders Keepers (Bill Hodges Trilogy #2)', 'Fables, Vol. 1: Legends in Exile (Fables #1)', 'Eureka Trivia 6.0', 'Drive: The Surprising Truth About What Motivates Us', 'Done Rubbed Out (Reightman & Bailey #1)', 'Doing It Over (Most Likely To #1)', 'Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals', 'Dark Notes', 'Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead', 'Close to You', 'Chasing Heaven: What Dying Taught Me About Living', 'Big Magic: Creative Living Beyond Fear', 'Becoming Wise: An Inquiry into the Mystery and Art of Living', 'Beauty Restored (Riley Family Legacy Novellas #3)', 'Batman: The Long Halloween (Batman)', 'Batman: The Dark Knight Returns (Batman)', "Ayumi's Violin", 'Anonymous', 'Amy Meets the Saints and Sages', 'Amid the Chaos', 'Amatus', 'Agnostic: A Spirited Manifesto', 'Zealot: The Life and Times of Jesus of Nazareth', 'You (You #1)', 'Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)', 'Wild Swans', 'Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond', 'Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity', "What's It Like in Space?: Stories from Astronauts Who've Been There", 'We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)', "Walt Disney's Alice in Wonderland", 'V for Vendetta (V for Vendetta Complete)', 'Until Friday Night (The Field Party #1)', 'Unbroken: A World War II Story of Survival, Resilience, and Redemption', 'Twenty Yawns', 'Through the Woods', 'This Is Where It Ends', 'The Year of Magical Thinking', 'The Wright Brothers', "The White Queen (The Cousins' War #1)", "The Wedding Pact (The O'Malleys #2)", 'The Time Keeper', 'The Testament of Mary', 'The Star-Touched Queen', 'The Songs of the Gods', 'The Song of Achilles', 'The Rosie Project (Don Tillman #1)', 'The Power of Habit: Why We Do What We Do in Life and Business', 'The Marriage of Opposites', 'The Lucifer Effect: Understanding How Good People Turn Evil', 'The Long Haul (Diary of a Wimpy Kid #9)', 'The Loney', 'The Literature Book (Big Ideas Simply Explained)', 'The Last Mile (Amos Decker #2)', 'The Immortal Life of Henrietta Lacks', 'The Hidden Oracle (The Trials of Apollo #1)', 'The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth', 'The Guilty (Will Robie #4)', 'The First Hostage (J.B. Collins #2)', 'The Dovekeepers', 'The Darkest Lie', 'The Bane Chronicles (The Bane Chronicles #1-11)', 'The Bad-Ass Librarians of Timbuktu: And Their Race to Save the Worldâ\x80\x99s Most Precious Manuscripts', 'The 14th Colony (Cotton Malone #11)', 'That Darkness (Gardiner and Renner #1)', 'Tastes Like Fear (DI Marnie Rome #3)', 'Take Me with You', 'Swell: A Year of Waves', 'Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)', 'Still Life with Bread Crumbs', 'Steve Jobs', 'Sorting the Beef from the Bull: The Science of Food Fraud Forensics', 'Someone Like You (The Harrisons #2)', 'So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)', 'Shtum', 'See America: A Celebration of Our National Parks & Treasured Sites', 'salt.', 'Robin War', 'Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)', 'Rain Fish', 'Quarter Life Poetry: Poems for the Young, Broke and Hangry', 'Pet Sematary', 'Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress', 'Once Was a Time', 'Old School (Diary of a Wimpy Kid #10)', 'No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon', 'Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)', 'My Name Is Lucy Barton', 'My Mrs. Brown', 'My Kind of Crazy', 'Mr. Mercedes (Bill Hodges Trilogy #1)', 'More Than Music (Chasing the Dream #1)', 'Made to Stick: Why Some Ideas Survive and Others Die', 'Luis Paints the World', 'Luckiest Girl Alive', 'Lowriders to the Center of the Earth (Lowriders in Space #2)', 'Love Is a Mix Tape (Music #1)', 'Looking for Lovely: Collecting the Moments that Matter', 'Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments', 'Let It Out: A Journey Through Journaling', 'Lady Midnight (The Dark Artifices #1)', "It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes", 'Island of Dragons (Unwanteds #7)', "I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction", 'I Am Pilgrim (Pilgrim #1)', 'Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened', 'Hush, Hush (Hush, Hush #1)', 'Hold Your Breath (Search and Rescue #1)', 'Hamilton: The Revolution', 'Greek Mythic History', 'God: The Most Unpleasant Character in All Fiction', 'Glory over Everything: Beyond The Kitchen House', 'Feathers: Displays of Brilliant Plumage', 'Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years', 'Every Last Word', 'Eligible (The Austen Project #4)', 'El Deafo', 'Eight Hundred Grapes', 'Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life', 'Eat Fat, Get Thin', "Don't Get Caught", 'Doctor Sleep (The Shining #2)', 'Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)', 'Dear Mr. Knightley', 'Daily Fantasy Sports', 'Crazy Love: Overwhelmed by a Relentless God', 'Cometh the Hour (The Clifton Chronicles #6)', 'Code Name Verity (Code Name Verity #1)', 'Clockwork Angel (The Infernal Devices #1)', 'City of Glass (The Mortal Instruments #3)', 'City of Fallen Angels (The Mortal Instruments #4)', 'City of Bones (The Mortal Instruments #1)', 'City of Ashes (The Mortal Instruments #2)', 'Cell', 'Catching Jordan (Hundred Oaks)', 'Carry On, Warrior: Thoughts on Life Unarmed', 'Carrie', 'Buying In: The Secret Dialogue Between What We Buy and Who We Are', 'Brain on Fire: My Month of Madness', 'Batman: Europa', 'Barefoot Contessa Back to Basics', "Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again", 'Balloon Animals', 'Art Ops Vol. 1', 'Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)', 'Angels Walking (Angels Walking #1)', 'Angels & Demons (Robert Langdon #1)', 'All the Light We Cannot See', 'Adulthood Is a Myth: A "Sarah\'s Scribbles" Collection', 'Abstract City', 'A Time of Torment (Charlie Parker #14)', 'A Study in Scarlet (Sherlock Holmes #1)', 'A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer', "A People's History of the United States", 'A Man Called Ove', 'A Distant Mirror: The Calamitous 14th Century', 'A Brush of Wings (Angels Walking #3)', '1491: New Revelations of the Americas Before Columbus', 'The Three Searches, Meaning, and the Story', 'Searching for Meaning in Gailana', 'Rook', 'My Kitchen Year: 136 Recipes That Saved My Life', '13 Hours: The Inside Account of What Really Happened In Benghazi', "Will You Won't You Want Me?", 'Tipping Point for Planet Earth: How Close Are We to the Edge?', 'The Star-Touched Queen', 'The Silent Sister (Riley MacPherson #1)', 'The Midnight Watch: A Novel of the Titanic and the Californian', 'The Lonely City: Adventures in the Art of Being Alone', 'The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore', 'The Golden Condom: And Other Essays on Love Lost and Found', 'The Epidemic (The Program 0.6)', 'The Dinner Party', 'The Diary of a Young Girl', 'The Children', 'Stars Above (The Lunar Chronicles #4.5)', 'Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas', 'Raspberry Pi Electronics Projects for the Evil Genius', 'Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two', 'Psycho: Sanitarium (Psycho #1.5)', 'Poisonous (Max Revere Novels #3)', 'One with You (Crossfire #5)', 'No Love Allowed (Dodge Cove #1)', 'Murder at the 42nd Street Library (Raymond Ambler #1)', 'Most Wanted', 'Love, Lies and Spies', 'How to Speak Golf: An Illustrated Guide to Links Lingo', 'Hide Away (Eve Duncan #20)', 'Furiously Happy: A Funny Book About Horrible Things', 'Everyday Italian: 125 Simple and Delicious Recipes', "Equal Is Unfair: America's Misguided Fight Against Income Inequality", 'Eleanor & Park', 'Dirty (Dive Bar #1)', 'Can You Keep a Secret? (Fear Street Relaunch #4)', 'Boar Island (Anna Pigeon #19)', 'A Paris Apartment', 'A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More', 'Troublemaker: Surviving Hollywood and Scientology', 'The Widow', 'The Sleep Revolution: Transforming Your Life, One Night at a Time', 'The Improbability of Love', 'The Art of Startup Fundraising', 'Take Me Home Tonight (Rock Star Romance #3)', 'Sleeping Giants (Themis Files #1)', 'Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena', 'Playing with Fire', 'Off the Hook (Fishing for Trouble #1)', 'Mothering Sunday', 'Mother, Can You Not?', 'M Train', 'Lilac Girls', 'Lies and Other Acts of Love', 'Lab Girl', 'Keep Me Posted', "It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle", 'Grey (Fifty Shades #4)', 'Exit, Pursued by a Bear', 'Daredevils', 'Cravings: Recipes for What You Want to Eat', 'Born for This: How to Find the Work You Were Meant to Do', 'Arena', 'Adultery', "A Mother's Reckoning: Living in the Aftermath of Tragedy", "A Gentleman's Position (Society of Gentlemen #3)", '11/22/63', '10% Happier: How I Tamed the Voice in My Head, Reduced Stress Without Losing My Edge, and Found Self-Help That Actually Works', '10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!', 'Without Shame', 'Watchmen', 'Unlimited Intuition Now', 'Underlying Notes', 'The Shack', 'The New Brand You: Your New Image Makes the Sale for You', 'The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York', 'The Flowers Lied', 'The Fabric of the Cosmos: Space, Time, and the Texture of Reality', 'The Book of Mormon', 'The Art and Science of Low Carbohydrate Living', 'The Alien Club', 'Suzie Snowflake: One beautiful flake (a self-esteem story)', 'Nap-a-Roo', 'NaNo What Now? Finding your editing process, revising your NaNoWriMo book and building a writing career through publishing and beyond', 'Modern Day Fables', "If I Gave You God's Phone Number....: Searching for Spirituality in America", 'Fruits Basket, Vol. 9 (Fruits Basket #9)', '

In [ ]:
# total books - 20 books on each of the 50 pages
print(len(title_list))

1000

In [ ]:
print(rating_list)

['Three', 'One', 'One', 'Four', 'Five', 'One', 'Four', 'Three', 'Four', 'One', 'Two', 'Four', 'Five', 'Five', 'Five', 'Three', 'One', 'One', 'Two', 'Two', 'One', 'Two', 'Three', 'Five', 'Five', 'Three', 'Three', 'Three', 'Five', 'Four', 'Five', 'Three', 'Five', 'One', 'Five', 'Three', 'Two', 'One', 'Four', 'Two', 'Three', 'Two', 'Five', 'Five', 'Two', 'One', 'Five', 'Four', 'Four', 'Three', 'One', 'One', 'Three', 'Four', 'Five', 'One', 'One', 'One', 'Four', 'Three', 'Four', 'Three', 'Four', 'Four', 'Three', 'Five', 'One', 'One', 'Four', 'Three', 'Three', 'One', 'Five', 'Four', 'Two', 'Two', 'Three', 'Two', 'Two', 'Three', 'Five', 'Five', 'One', 'Two', 'Three', 'Four', 'One', 'One', 'Three', 'Two', 'Two', 'Two', 'Four', 'Two', 'Three', 'Two', 'One', 'Two', 'Five', 'Four', 'Five', 'Two', 'Three', 'One', 'One', 'Two', 'Three', 'Four', 'One', 'Two', 'Two', 'Four', 'Three', 'Four', 'Four', 'Five', 'Three', 'Two', 'Two', 'Two', 'One', 'One', 'Five', 'One', 'Five', 'Four', 'One', 'Five', 'Four', 'Four', 'Two', 'Three', 'Three', 'One', 'One', 'Four', 'One', 'Four', 'Five', 'Four', 'One', 'Four', 'Five', 'Two', 'One', 'Two', 'Two', 'Five', 'Four', 'Three', 'One', 'Two', 'One', 'Four', 'One', 'One', 'Two', 'One', 'Two', 'One', 'Three', 'Five', 'Five', 'Two', 'Three', 'Two', 'Four', 'Two', 'Two', 'Two', 'Three', 'One', 'Five', 'One', 'Five', 'One', 'Four', 'One', 'One', 'Five', 'Five', 'One', 'Two', 'Three', 'Five', 'Two', 'Four', 'One', 'Two', 'Four', 'Five', 'One', 'One', 'Five', 'Four', 'Four', 'Four', 'Five', 'Three', 'Three', 'Five', 'Three', 'Four', 'Two', 'Three', 'Two', 'Two', 'Two', 'Five', 'Two', 'Four', 'Three', 'One', 'Five', 'Five', 'Three', 'Five', 'Four', 'Two', 'Four', 'Four', 'Two', 'One', 'Five', 'Four', 'Two', 'Two', 'Two', 'Two', 'Two', 'Two', 'Four', 'Five', 'Three', 'Five', 'Four', 'Five', 'Five', 'Five', 'One', 'Three', 'Four', 'One', 'One', 'One', 'Three', 'Two', 'Two', 'Two', 'Three', 'Two', 'Three', 'One', 'Five', 'Four', 'One', 'One', 'One', 'One', 'Three', 'One', 'Five', 'Three', 'Five', 'Four', 'Five', 'Four', 'Four', 'Three', 'Four', 'Three', 'Two', 'Three', 'Five', 'Three', 'Three', 'Two', 'Five', 'Two', 'Two', 'One', 'Three', 'One', 'One', 'Two', 'Five', 'Three', 'Three', 'Two', 'One', 'Five', 'Four', 'Five', 'Five', 'One', 'One', 'Four', 'Four', 'Five', 'Three', 'One', 'Three', 'Five', 'Five', 'Three', 'Three', 'Four', 'Three', 'Three', 'Five', 'Four', 'Five', 'Two', 'One', 'Two', 'Five', 'Five', 'One', 'Two', 'Three', 'Four', 'One', 'Four', 'Four', 'One', 'One', 'Four', 'Three', 'Three', 'Two', 'Four', 'Five', 'Two', 'One', 'Five', 'Three', 'Three', 'Four', 'Two', 'Three', 'Five', 'Two', 'Five', 'Five', 'Two', 'Two', 'Two', 'One', 'Three', 'One', 'Three', 'Three', 'One', 'Four', 'Two', 'One', 'Three', 'One', 'Five', 'Five', 'One', 'Two', 'Four', 'One', 'Five', 'Two', 'Three', 'Three', 'Two', 'Three', 'Four', 'One', 'Five', 'Three', 'Four', 'Four', 'Four', 'Three', 'Two', 'Five', 'One', 'Four', 'Five', 'One', 'Five', 'Four', 'One', 'Three', 'Four', 'One', 'Two', 'Two', 'Four', 'One', 'Three', 'Three', 'One', 'Two', 'Three', 'Three', 'Two', 'Five', 'One', 'Two', 'One', 'One', 'Four', 'Three', 'Four', 'Four', 'Three', 'Three', 'Five', 'Four', 'Five', 'Three', 'Five', 'Three', 'Two', 'Five', 'Five', 'Four', 'Four', 'Two', 'One', 'Five', 'Four', 'Two', 'One', 'Three', 'Five', 'One', 'Five', 'One', 'Four', 'Two', 'One', 'Four', 'Three', 'One', 'Two', 'Four', 'Three', 'Three', 'Two', 'Three', 'One', 'Two', 'Two', 'Five', 'Three', 'Four', 'Two', 'One', 'One', 'One', 'One', 'Five', 'Three', 'Five', 'Five', 'Three', 'One', 'Four', 'Five', 'Five', 'Two', 'Three', 'Two', 'Three', 'Five', 'Two', 'Five', 'One', 'Four', 'One', 'One', 'Four', 'Two', 'Four', 'Two', 'Five', 'One', 'One', 'Four', 'Three', 'Two', 'Four', 'Four', 'Three', 'Two', 'Five', 'Three', 'Two', 'Five', 'Two', 'Three', 'One', 'One', 'Four', 'Four', 'Four', 'Four', 'Three', 'One', 'One', 'Three', 'Three', 'Four', 'Five', 'Two', 'Four', 'Five', 'Two', 'Three', 'Four', 'Three', 'One', 'Two', 'One', 'Four', 'Five', 'Three', 'Three', 'Two', 'Four', 'Five', 'Five', 'Four', 'Four', 'Two', 'Five', 'One', 'Three', 'Two', 'Five', 'Four', 'Five', 'Two', 'One', 'Three', 'Five', 'Two', 'Five', 'Four', 'Five', 'Two', 'Three', 'Four', 'Four', 'Two', 'Four', 'One', 'Five', 'One', 'One', 'Three', 'One', 'Two', 'Five', 'Five', 'Two', 'Three', 'Four', 'One', 'Three', 'One', 'Two', 'Four', 'Five', 'Two', 'Three', 'Four', 'Four', 'Four', 'Three', 'Four', 'Three', 'Three', 'Four', 'Four', 'Four', 'Two', 'Four', 'Four', 'One', 'One', 'Four', 'Two', 'Four', 'Five', 'One', 'Five', 'Three', 'Four', 'Three', 'Three', 'One', 'Five', 'Two', 'One', 'Five', 'Four', 'Two', 'Three', 'One', 'Four', 'Five', 'Five', 'Three', 'Three', 'Two', 'Four', 'Five', 'One', 'Four', 'Two', 'Three', 'Four', 'Five', 'Five', 'Five', 'Two', 'One', 'One', 'One', 'One', 'One', 'One', 'Two', 'Five', 'Five', 'One', 'Three', 'One', 'Five', 'Five', 'Five', 'Five', 'Two', 'Four', 'One', 'Two', 'Four', 'Three', 'Four', 'Three', 'Two', 'Three', 'Five', 'Three', 'Five', 'Two', 'Four', 'Two', 'Two', 'Two', 'Three', 'Five', 'Five', 'Five', 'Five', 'Five', 'Three', 'Five', 'Four', 'Four', 'Four', 'Two', 'Four', 'Three', 'Three', 'Four', 'Four', 'Five', 'One', 'Three', 'One', 'One', 'Four', 'Two', 'One', 'Two', 'Three', 'Three', 'One', 'Five', 'Three', 'One', 'Five', 'One', 'Four', 'One', 'Three', 'One', 'Three', 'One', 'Five', 'Three', 'One', 'Three', 'Five', 'Three', 'Two', 'One', 'One', 'Two', 'Two', 'Two', 'One', 'Three', 'One', 'Three', 'Three', 'Four', 'One', 'Two', 'One', 'Two', 'One', 'Five', 'Five', 'Four', 'One', 'Three', 'One', 'One', 'Five', 'Three', 'One', 'Two', 'Three', 'One', 'Four', 'Three', 'Five', 'Two', 'One', 'Two', 'Five', 'Three', 'Two', 'Four', 'One', 'Five', 'Three', 'Two', 'One', 'Three', 'One', 'Three', 'Two', 'One', 'Three', 'Four', 'Four', 'Five', 'One', 'Four', 'Five', 'Two', 'One', 'Four', 'Five', 'One', 'Two', 'One', 'Two', 'Five', 'Five', 'Two', 'Three', 'One', 'Two', 'Three', 'One', 'Five', 'One', 'Two', 'Two', 'Two', 'Four', 'Four', 'One', 'Five', 'Four', 'Three', 'Four', 'Two', 'Three', 'Three', 'Four', 'One', 'Three', 'One', 'Two', 'One', 'Three', 'Two', 'Two', 'One', 'One', 'Three', 'Three', 'One', 'One', 'Two', 'Two', 'Two', 'Two', 'Three', 'Two', 'Five', 'Two', 'One', 'One', 'Four', 'One', 'Five', 'Five', 'One', 'One', 'Three', 'Five', 'Five', 'Three', 'Four', 'One', 'Two', 'Three', 'Two', 'One', 'Two', 'Two', 'Four', 'Four', 'One', 'Five', 'Five', 'Four', 'Two', 'Two', 'Three', 'Four', 'Five', 'One', 'Three', 'Three', 'One', 'One', 'Three', 'One', 'Five', 'Five', 'One', 'One', 'Five', 'Five', 'One', 'Two', 'Two', 'One', 'Two', 'Two', 'Five', 'Five', 'Three', 'Two', 'Five', 'One', 'One', 'One', 'Five', 'Two', 'Two', 'Five', 'Two', 'Four', 'Three', 'One', 'Five', 'Two', 'Four', 'Five', 'Two', 'Five', 'One', 'One', 'Two', 'Three', 'One', 'Three', 'One', 'Three', 'One', 'Four', 'Five', 'Three', 'Five', 'One', 'Five', 'Four', 'Four', 'Five', 'Three', 'Three', 'Five', 'One', 'Two', 'Four', 'Five', 'Two', 'One', 'Five', 'Two', 'Five', 'Four', 'Five', 'Three', 'One', 'Three', 'Three', 'Three', 'Three', 'Four', 'One', 'Three', 'One', 'Two', 'One', 'Two', 'One', 'Five', 'Five', 'Five', 'Three', 'One', 'Four', 'Three', 'Three', 'Three', 'Three', 'Four', 'Two', 'Three', 'Three', 'Three', 'One', 'Three', 'Four', 'Two', 'One', 'One', 'Two', 'Five', 'One', 'Four', 'Three', 'One', 'Two', 'Three', 'Two', 'Five', 'Two', 'Four', 'Two', 'Four', 'Two', 'One', 'Four', 'Three', 'Three', 'Five', 'Five', 'Four', 'Four', 'Three', 'Four', 'Four', 'Five', 'Two', 'Three', 'Three', 'Two', 'Three', 'Five', 'Four', 'Three', 'One', 'Five', 'One', 'Four', 'Three', 'Five', 'One', 'One', 'Four', 'Five', 'One', 'Five']

In [ ]:
print(len(rating_list))

1000

**All other information about each book is available on respective book's URL. Let's check any random book and try to access the information.**

In [ ]:
# we already know the url
soup.select('article h3 a')[0]['href']

'in-her-wake_980/index.html'

In [ ]:
# new request for each url
new_request = requests.get('https://books.toscrape.com/catalogue/in-her-wake_980/index.html')

In [ ]:
# new soup object for each book url
soup_new = bs4.BeautifulSoup(new_request.text)
soup_new

In [ ]:
# visit URL and go the Product Information table
soup_new.select('tr')

[<tr>
 <th>UPC</th><td>23356462d1320d61</td>
 </tr>,
 <tr>
 <th>Product Type</th><td>Books</td>
 </tr>,
 <tr>
 <th>Price (excl. tax)</th><td>Â£12.84</td>
 </tr>,
 <tr>
 <th>Price (incl. tax)</th><td>Â£12.84</td>
 </tr>,
 <tr>
 <th>Tax</th><td>Â£0.00</td>
 </tr>,
 <tr>
 <th>Availability</th>
 <td>In stock (19 available)</td>
 </tr>,
 <tr>
 <th>Number of reviews</th>
 <td>0</td>
 </tr>]

In [ ]:
# feature of book
soup_new.select('tr th')

[<th>UPC</th>,
 <th>Product Type</th>,
 <th>Price (excl. tax)</th>,
 <th>Price (incl. tax)</th>,
 <th>Tax</th>,
 <th>Availability</th>,
 <th>Number of reviews</th>]

In [ ]:
# accessing random feature
soup_new.select('tr th')[2].text

'Price (excl. tax)'

In [ ]:
# value of that feature
soup_new.select('tr td')

[<td>23356462d1320d61</td>,
 <td>Books</td>,
 <td>Â£12.84</td>,
 <td>Â£12.84</td>,
 <td>Â£0.00</td>,
 <td>In stock (19 available)</td>,
 <td>0</td>]

In [ ]:
# accessing value of random feature
soup_new.select('tr td')[2].text

'Â£12.84'

**Using `for` loop to get all the information about each book in the form of dataframe**

In [ ]:
%%time

new_df = pd.DataFrame()  # empty dataframe
index_num= 0             # index of dataframe

for page_num in range(1,51):    # total pages
    request = requests.get(f'http://books.toscrape.com/catalogue/page-{page_num}.html')  # url of each page
    soup_ = bs4.BeautifulSoup(request.text)
    book_info_list = soup_.select('article h3 a')   # all books on that page

    for n in range(0,20):
        res = requests.get('http://books.toscrape.com/catalogue/'+ book_info_list[n]['href']) # url of each book in above page
        soup = bs4.BeautifulSoup(res.text, 'lxml')

        book_features_column_list = soup.select('tr th')   # book features like price, rating of each book
        book_column_values = soup.select('tr td')          # values of that features

        column_names = [ item.text for item in book_features_column_list ]

        column_values = [item.text for item in book_column_values ]

        d = dict(zip(column_names, column_values))  # making dictionary with features as columns and values as rows

        df = pd.DataFrame(d, index = [index_num + n])
        new_df = new_df.append(df)   # append df of every page

    index_num += 20  # index for each page to be incremented by 20 as zero_base index since there are 20 books on each page

In [ ]:
new_df

,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
0,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0
1,90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0
2,6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0
3,e00eb4fd7b871a48,Books,Â£47.82,Â£47.82,Â£0.00,In stock (20 available),0
4,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0
...,...,...,...,...,...,...,...
652,6587f46697fc4443,Books,Â£14.82,Â£14.82,Â£0.00,In stock (4 available),0
653,45033bdf3d9ed158,Books,Â£16.81,Â£16.81,Â£0.00,In stock (4 available),0
654,c65ee14957c0fa5c,Books,Â£28.23,Â£28.23,Â£0.00,In stock (4 available),0
655,ff2dffba388d9922,Books,Â£52.11,Â£52.11,Â£0.00,In stock (4 available),0
656,df53c2948b32bde3,Books,Â£27.88,Â£27.88,Â£0.00,In stock (4 available),0

In [ ]:
print(new_df.shape)

(1000, 7)

In [ ]:
# adding new columns in a dataframe
new_df["Rating"] = rating_list
new_df["Title"] = title_list
new_df

,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,Rating,Title
0,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three,A Light in the Attic
1,90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0,One,Tipping the Velvet
2,6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0,One,Soumission
3,e00eb4fd7b871a48,Books,Â£47.82,Â£47.82,Â£0.00,In stock (20 available),0,Four,Sharp Objects
4,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0,Five,Sapiens: A Brief History of Humankind
...,...,...,...,...,...,...,...,...,...
995,cd2a2a70dd5d176d,Books,Â£55.53,Â£55.53,Â£0.00,In stock (1 available),0,One,Alice in Wonderland (Alice's Adventures in Won...
996,bfd5e1701c862ac3,Books,Â£57.06,Â£57.06,Â£0.00,In stock (1 available),0,Four,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)"
997,19fec36a1dfb4c16,Books,Â£16.97,Â£16.97,Â£0.00,In stock (1 available),0,Five,A Spy's Devotion (The Regency Spies of London #1)
998,f684a82adc49f011,Books,Â£53.98,Â£53.98,Â£0.00,In stock (1 available),0,One,1st to Die (Women's Murder Club #1)
999,228ba5e7577e1d49,Books,Â£26.08,Â£26.08,Â£0.00,In stock (1 available),0,Five,"1,000 Places to See Before You Die"

In [ ]:
# to select the category of the book
soup_new.select('ul')

In [ ]:
# we use index since it is a list
(soup_new.select('ul'))[0]

<ul class="breadcrumb">
<li>
<a href="../../index.html">Home</a>
</li>
<li>
<a href="../category/books_1/index.html">Books</a>
</li>
<li>
<a href="../category/books/thriller_37/index.html">Thriller</a>
</li>
<li class="active">In Her Wake</li>
</ul>

In [ ]:
# from the HTML code above, as we can see 'a' tag has the genre of the book, so we select that tag
(soup_new.select('ul'))[0].select('a')

[<a href="../../index.html">Home</a>,
 <a href="../category/books_1/index.html">Books</a>,
 <a href="../category/books/thriller_37/index.html">Thriller</a>]

In [ ]:
# genre is present at the second index position of above list
(soup_new.select('ul'))[0].select('a')[2]

In [ ]:
(soup_new.select('ul'))[0].select('a')[2].text

'Thriller'

**Using `for` loop to get the categories of each book in the form of a list**

In [ ]:
%%time

category_list = []

for page_num in range(1,51):
    request = requests.get(f'http://books.toscrape.com/catalogue/page-{page_num}.html')  #url of each page
    soup_ = bs4.BeautifulSoup(request.text)
    book_info_list = soup_.select('article h3 a')

    for n in range(0,20):
        res = requests.get('http://books.toscrape.com/catalogue/'+ book_info_list[n]['href']) #url of each book in above page
        soup = bs4.BeautifulSoup(res.text)

        category = (soup.select('ul'))[0].select('a')[2].text

        category_list.append(category)

len(category_list)

Wall time: 9min 53s

1000

In [ ]:
print(category_list[0:10])

['Poetry', 'Historical Fiction', 'Fiction', 'Mystery', 'History', 'Young Adult', 'Business', 'Default', 'Default', 'Poetry']

In [ ]:
print(len(category_list))

1000

In [ ]:
# adding category as a column in the above dataframe
final_dataset = new_df.copy()

final_dataset['Category'] = category_list

final_dataset.head()

,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,Rating,Title,Category
0,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three,A Light in the Attic,Poetry
1,90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0,One,Tipping the Velvet,Historical Fiction
2,6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0,One,Soumission,Fiction
3,e00eb4fd7b871a48,Books,Â£47.82,Â£47.82,Â£0.00,In stock (20 available),0,Four,Sharp Objects,Mystery
4,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0,Five,Sapiens: A Brief History of Humankind,History

In [ ]:
print(final_dataset.shape)

(1000, 10)

**To store this data in the form of `csv` file**

In [ ]:
final_dataset.to_csv('scraped_dataset.csv')

NameError: ignored